[package]
name = "turso-mini-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[lib]
name = "turso_mini_core"
path = "mod.rs"

[dependencies]
bitflags.workspace = true
